//per semplicità ho usato solo ingredienti ecc piu famosi e usati
export const SPIRITS = [
    "Amaretto",
    "Amaro",
    "Aperol",
    "Aquavit",
    "Assenzio",
    "Baileys",
    "Bitter",
    "Bourbon",
    "Brandy",
    "Cachaça",
    "Campari",
    "Champagne",
    "Chartreuse gialla",
    "Chartreuse verde",
    "Cognac",
    "Cointreau",
    "Crème de cacao",
    "Crème de cassis",
    "Crème de menthe",
    "Cynar",
    "Drambuie",
    "Fernet",
    "Frangelico",
    "Galliano",
    "Gin",
    "Grand Marnier",
    "Grappa",
    "Irish whiskey",
    "Jägermeister",
    "Kahlúa",
    "Limoncello",
    "Liquore al caffè",
    "Malibu",
    "Maraschino",
    "Mezcal",
    "Midori",
    "Ouzo",
    "Pastis",
    "Pisco",
    "Porto",
    "Prosecco",
    "Rum agricolo",
    "Rum bianco",
    "Rum scuro",
    "Rum speziato",
    "Rye whiskey",
    "Sambuca",
    "Scotch",
    "Southern Comfort",
    "Tequila",
    "Triple sec",
    "Vermouth bianco",
    "Vermouth rosso",
    "Vermouth secco",
    "Vodka",
    "Whisky"
].sort((a, b) => a.localeCompare(b, "it"));

export const NON_ALCOHOLIC = [
    "Acqua frizzante",
    "Acqua tonica",
    "Albume d'uovo",
    "Angostura",
    "Bitter analcolico",
    "Caffè",
    "Coca-Cola",
    "Crema di cocco",
    "Estratto di vaniglia",
    "Ginger ale",
    "Ginger beer",
    "Kombucha",
    "Latte",
    "Latte di cocco",
    "Limonata",
    "Panna",
    "Sciroppo di granatina",
    "Sciroppo di orzata",
    "Sciroppo di zenzero",
    "Sciroppo di zucchero",
    "Soda",
    "Succo d'ananas",
    "Succo d'arancia",
    "Succo di cocco",
    "Succo di lime",
    "Succo di limone",
    "Succo di melograno",
    "Succo di mirtillo",
    "Succo di pesca",
    "Succo di pomodoro",
    "Succo di pompelmo",
    "Tè",
    "Tè freddo",
    "Yogurt"
].sort((a, b) => a.localeCompare(b, "it"));

export const EXTRAS = [
    "Basilico",
    "Cannella",
    "Cannuccia",
    "Cetriolo",
    "Ciliegina",
    "Ghiaccio",
    "Ghiaccio tritato",
    "Menta fresca",
    "Oliva",
    "Pepe nero",
    "Peperoncino",
    "Rosmarino",
    "Sale",
    "Sale rosa",
    "Salsa Worcestershire",
    "Scorza d'arancia",
    "Scorza di lime",
    "Scorza di limone",
    "Spicchio di lime",
    "Spicchio di limone",
    "Spicchio d'arancia",
    "Tabasco",
    "Zenzero fresco",
    "Zucchero",
    "Zucchero di canna"
].sort((a, b) => a.localeCompare(b, "it"));

export function isAlcoholic(ingredientName) {
    return SPIRITS.includes(ingredientName);
}

export function isExtra(ingredientName) {
    return EXTRAS.includes(ingredientName);
}
