export const SPIRITS = [
    "Amaretto",
    "Aperol",
    "Assenzio",
    "Baileys",
    "Bitter",
    "Bourbon",
    "Brandy",
    "Cachaça",
    "Campari",
    "Champagne",
    "Cognac",
    "Cointreau",
    "Crème de cacao",
    "Crème de cassis",
    "Crème de menthe",
    "Fernet",
    "Gin",
    "Grand Marnier",
    "Grappa",
    "Liquore al caffè",
    "Malibu",
    "Mezcal",
    "Prosecco",
    "Rum agricolo",
    "Rum bianco",
    "Rum scuro",
    "Rye whiskey",
    "Sambuca",
    "Scotch",
    "Tequila",
    "Triple sec",
    "Vermouth bianco",
    "Vermouth rosso",
    "Vermouth secco",
    "Vodka",
    "Whisky"
].sort((a, b) => a.localeCompare(b, "it"));

export const NON_ALCOHOLIC = [
    "Acqua tonica",
    "Albume d'uovo",
    "Angostura",
    "Caffè",
    "Coca-Cola",
    "Crema di cocco",
    "Ginger ale",
    "Ginger beer",
    "Latte",
    "Panna",
    "Sciroppo di orzata",
    "Sciroppo di zenzero",
    "Sciroppo di zucchero",
    "Soda",
    "Succo d'ananas",
    "Succo d'arancia",
    "Succo di lime",
    "Succo di limone",
    "Succo di melograno",
    "Succo di mirtillo",
    "Succo di pesca",
    "Succo di pomodoro",
    "Succo di pompelmo",
    "Tè"
].sort((a, b) => a.localeCompare(b, "it"));

export const EXTRAS = [
    "Basilico",
    "Cannella",
    "Cannuccia",
    "Cetriolo",
    "Ciliegina",
    "Ghiaccio",
    "Ghiaccio tritato",
    "Menta fresca",
    "Oliva",
    "Pepe nero",
    "Peperoncino",
    "Rosmarino",
    "Sale",
    "Sale rosa",
    "Salsa Worcestershire",
    "Scorza d'arancia",
    "Scorza di lime",
    "Scorza di limone",
    "Spicchio di lime",
    "Spicchio di limone",
    "Spicchio d'arancia",
    "Tabasco",
    "Zenzero fresco",
    "Zucchero",
    "Zucchero di canna"
].sort((a, b) => a.localeCompare(b, "it"));

export function isAlcoholic(ingredientName) {
    return SPIRITS.includes(ingredientName);
}

export function isExtra(ingredientName) {
    return EXTRAS.includes(ingredientName);
}
